#!/bin/bash
dir=~/works/maplebeats.github.com
flash_time=5
refresh(){
	jekyll
}
cd $dir
echo "正在以 $flash_time s刷新jekyll文件"
refresh
echo " 第1次刷新"
n=2
while :
do
	sleep $flash_time
	refresh
	echo "第$n次刷新"
	((n++))
done
