#!/bin/bash
#this is a shell for playing anime videos.
#maplebeats'shell

temp_file=/tmp/cdb.$$

video_time(){
	echo -e "at frist,you should cd in your video directory"
	echo -e "please input the period at the end of OP(Separated by Spaces)"
  read open_time_min open_time_sed
  open_time=`expr 60 \* $open_time_min + $open_time_sed`
  echo -e "please input the period at the open of ED(Separated by Spaces)"
  read end_time_min end_time_sed
  end_time=`expr 60 \* $end_time_min + $end_time_sed - $open_time`
  echo "the mplayer will play $open_time_min : $open_time_sed to $end_time_min : $end_time_sed"
return 0
}

creat_lst () {                      
find . \( -name "*.rmvb" -or -name "*.mp4" \) -type f | vim -c 'sort nr /\d\+/' -c 'w '$temp_file'' -c 'q' - && cat $temp_file >anime.lst && rm $temp_file
#find . \( -name "*.rmvb" \) -type f | sort > anime.lst
}

skip_open(){
mplayer -fs -ss $open_time -playlist anime.lst >/dev/null 2>&1
}

skip_end(){
sleep $end_time && killall mplayer >/dev/null 2>&1 && sed -i '1d' anime.lst && play_video >/dev/null
}

play_video(){
if [ -s anime.lst ];then         
  skip_end& 
  skip_open
else
rm -f anime.lst
echo "end of the videos!"
exit 0
fi
}

lst_presence(){                       
if [ -f ./anime.lst ]
then 
 return 0
else
 return 1
fi
}

video_time                      
if lst_presence         
then
  	play_video
else
 	creat_lst
	play_video
fi
exit 0
