#!/bin/bash
#this is a shell for playing anime videos.
#maplebeats'shell

temp_file=/tmp/cdb.$$

video_time(){
	if [ ! -f ./anime.tm ];then
		echo -e "please input the period at the end of OP(Separated by Spaces)"
		read open_time_min open_time_sed
		open_time=`expr 60 \* $open_time_min + $open_time_sed`
		echo $open_time >anime.tm
		echo -e "please input the period at the open of ED(Separated by Spaces)"
		read end_time_min end_time_sed 
		end_time=`expr 60 \* $end_time_min + $end_time_sed - $open_time`
		echo $end_time >>anime.tm
		echo "the mplayer will play $open_time_min : $open_time_sed to $end_time_min : $end_time_sed"
	else
	  n=0
	  while read line
	  do
		  array[$n]=$line
		  ((n++))
	  done < anime.tm
	  open_time=${array[0]}
	  end_time=${array[1]}
  fi
}

creat_lst () {
	rm -f $temp_file
	find . \( -name "*.rmvb" -or -name "*.mp4" \) -type f | vim -c 'sort nr /\d\+/' -c 'w '$temp_file'' -c 'q' - && cat $temp_file >anime.lst && rm $temp_file
	#find . \( -name "*.rmvb" \) -type f | sort > anime.lst
}

skip_open(){
	mplayer -fs -ss $open_time -playlist anime.lst >/dev/null 2>&1
}

skip_end(){
	sleep $end_time && killall mplayer >/dev/null 2>&1 && sed -i '1d' anime.lst && play_video >/dev/null
}

play_video(){
	if [ -s anime.lst ];then         
		skip_end& 
		skip_open
	else
		rm -f anime.lst
		echo "end of the videos!"
		exit 0
	fi
}

ln_shell(){
if [ -f /usr/bin/playV ]
then
	echo "let's begin"
else
	echo "move the shell to /usr/bin(need root)(yes/no?)"
	read ans
	case "$ans" in
		yes | Y | Yes | YES )
		sudo cp ./playV /usr/bin
		#sudo ln -s ./playV /usr/bin/playV
		echo "Ok!let's begin" ;;
		n* | N* )	echo "let'go !" ;;
		* )		echo "sorry,answer no recognized";;
	esac

fi
}

ln_shell
video_time                      
if [ -f ./anime.lst ]        
then
	play_video
else
 	creat_lst
	play_video
fi
