#!/bin/bash
LANG=zh
dir=~/works/maplebeats.github.com/_posts
cd $dir
temp=/tmp/post.$$
editor=gedit

date +%F >$temp
echo $*.textile >>$temp
xargs <$temp |tee $temp
cat $temp|sed '/ \+/s//-/g' |tee $temp
touch `cat $temp`
echo "输入文章title"
read post_title
echo "---
layout: post
title: $post_title
---
" >`cat $temp`
$editor `cat $temp`
echo "Are you sure to push to github?(N)"
read ans
echo "<p class=date>Posted on `date +%c` by \"maplebeats\":http://maplebeats.com/me</p>" >> `cat $temp`
case "$ans" in 
	n* | N* )
		exit 0
		;;
	*)
		git add .
		git commit -a -m "`date` $*"
		git push
		;;
esac
exit 0
